name: Git Release

on: workflow_dispatch

jobs:
    release:
        permissions: write-all
        strategy:
            fail-fast: false
            matrix:
                package:
                    - drizzle-prisma-generator
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v4

            - uses: wyvox/action-setup-pnpm@v3
              name: Setup pnpm
              with:
                args: '--frozen-lockfile'
                node-registry-url: "https://registry.npmjs.org"
                node-version: 20
                pnpm-version: 10

            - name: Build
              run: |
                  pnpm build

            - name: Pack
              run: |
                  npm run pack

            - name: List files in the repository
              run: ls -a
            
            - name: Run @arethetypeswrong/cli
              run: |
                  pnpm attw package.tgz

            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                name: package
                path: package.tgz

            - name: Create Release
              id: create_release
              uses: softprops/action-gh-release@v2.0.5
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: v1-${{ github.run_number }}
                name: v1-${{ github.run_number }}
                files: package.tgz